[variables]
NODE_VERSION = "22"

[phases.setup]
nixPkgs = ['nodejs-22_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'node --version',
  'npx prisma generate',
  'npx tsc'
]

[start]
cmd = 'npm start'